CC = gcc
CFLAGS = -Wall

TARGET_APP = app
TARGET_SLAVE = slave
TARGET_VISTA = vista
TARGET_ALL = $(TARGET_APP) $(TARGET_SLAVE) $(TARGET_VISTA)
SOURCES_APP = app.c
SOURCES_SLAVE = slave.c
SOURCES_VISTA = vista.c
SOURCES_ALL = $(SOURCES_APP) $(SOURCES_SLAVE) $(SOURCES_VISTA)
OBJECTS_APP = $(SOURCES_APP:.c=.o)
OBJECTS_SLAVE = $(SOURCES_SLAVE:.c=.o)
OBJECTS_VISTA = $(SOURCES_VISTA:.c=.o)
OBJECTS_ALL = $(OBJECTS_APP) $(OBJECTS_SLAVE) $(OBJECTS_VISTA)

all: $(TARGET_ALL)

$(TARGET_APP): $(OBJECTS_APP)
	$(CC) $(CFLAGS) -o $(TARGET_APP) $(OBJECTS_APP)

$(TARGET_SLAVE): $(OBJECTS_SLAVE)
	$(CC) $(CFLAGS) -o $(TARGET_SLAVE) $(OBJECTS_SLAVE)

$(TARGET_VISTA): $(OBJECTS_VISTA)
	$(CC) $(CFLAGS) -o $(TARGET_VISTA) $(OBJECTS_VISTA)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS_ALL) $(TARGET_ALL) result.txt