CC = gcc
CFLAGS = -Wall

TARGET_APP = app
TARGET_SLAVE = slave
TARGET_VIEW = view
TARGET_ALL = $(TARGET_APP) $(TARGET_SLAVE) $(TARGET_VIEW)
SOURCES_APP = app.c
SOURCES_SLAVE = slave.c
SOURCES_VIEW = view.c
SOURCES_ADTS = slaveCDT.c syncdShmCDT.c
VISTA_ADTS = syncdShmCDT.c
SOURCES_ALL = $(SOURCES_APP) $(SOURCES_SLAVE) $(SOURCES_VIEW)
OBJECTS_APP = $(SOURCES_APP:.c=.o)
OBJECTS_SLAVE = $(SOURCES_SLAVE:.c=.o)
OBJECTS_VIEW = $(SOURCES_VIEW:.c=.o)
OBJECTS_ALL = $(OBJECTS_APP) $(OBJECTS_SLAVE) $(OBJECTS_VIEW)

all: $(TARGET_ALL)

$(TARGET_APP): $(OBJECTS_APP)
	$(CC) $(CFLAGS) -o $(TARGET_APP) $(OBJECTS_APP) $(SOURCES_ADTS)

$(TARGET_SLAVE): $(OBJECTS_SLAVE)
	$(CC) $(CFLAGS) -o $(TARGET_SLAVE) $(OBJECTS_SLAVE) $(SOURCES_ADTS)

$(TARGET_VIEW): $(OBJECTS_VIEW)
	$(CC) $(CFLAGS) -o $(TARGET_VIEW) $(OBJECTS_VIEW) $(VISTA_ADTS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS_ALL) $(TARGET_ALL) result.txt